sudo: true                  # Required to install packages

env:
  global:
    - DOCKER_VERSION=1.7.1  # Install Docker version 1.7.1
    - DOCKER_VERSION=get.docker.com  # Install Docker using get.docker.com (may break)

    - BRANCH=stable         # Use 'stable' branch
    - BRANCH=develop        # Use 'develop' branch

    - QUIET=1               # Less verbose logging
    - UML_FIG=0             # Don't install fig
    - UML_DOCKERCOMPOSE=1   # Install docker-compose

language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

install:
  # Install https://github.com/moul/travis-docker toolchain
  - sudo apt-get update
  - sudo apt-get install -y wget
  - wget -qO- https://get.docker.com/ | sudo sh
  - composer self-update
  - composer up
  #  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - make test
